twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/image': image
        '%kernel.project_dir%/public/css' : css

when@test:
    twig:
        strict_variables: true
